### **Importing the required packages**

In [ ]:
import numpy as np
import pandas as pd

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, roc_auc_score
from sklearn.preprocessing import StandardScaler, LabelEncoder

### **Reading and Exploring the Data**

In [ ]:
data = pd.read_csv('nba_final.csv')

In [ ]:
data.head() #print the top 5 rows of the dataframe

,Rk,Player.x,Player_ID,Pos1,Pos2,Age,Tm,G,GS,MP,...,Conference,Role,Fvot,FRank,Pvot,PRank,Mvot,MRank,Score,Play
0,170,A.J. Hammons,hammoaj01,C,NaN,24,DAL,22,0,7.4,...,West,Front,786,123,NaN,NaN,NaN,NaN,83.5,No
1,58,Aaron Brooks,brookaa01,PG,NaN,32,IND,65,0,13.8,...,Est,Back,2474,64,NaN,NaN,NaN,NaN,48.2,No
2,157,Aaron Gordon,gordoaa01,SF,NaN,21,ORL,80,72,28.7,...,Est,Front,22774,29,NaN,NaN,NaN,NaN,40.0,No
3,352,Adreian Payne,paynead01,PF,NaN,25,MIN,18,0,7.5,...,West,Front,861,120,1.0,52.0,NaN,NaN,75.5,No
4,10,Al-Farouq Aminu,aminual01,PF,NaN,26,POR,61,25,29.1,...,West,Front,4971,69,7.0,23.0,NaN,NaN,42.8,No

In [ ]:
data.shape  #print the number of rows and columns in the dataframe

(1408, 45)

In [ ]:
data.dtypes #print the datatype of the values in each column

Rk              int64
Player.x       object
Player_ID      object
Pos1           object
Pos2           object
Age             int64
Tm             object
G               int64
GS              int64
MP            float64
FG            float64
FGA           float64
FG.           float64
X3P           float64
X3PA          float64
X3P.          float64
X2P           float64
X2PA          float64
X2P.          float64
eFG.          float64
FT            float64
FTA           float64
FT.           float64
ORB           float64
DRB           float64
TRB           float64
AST           float64
STL           float64
BLK           float64
TOV           float64
PF            float64
PTS           float64
Salary        float64
mean_views    float64
Season         object
Conference     object
Role           object
Fvot            int64
FRank           int64
Pvot          float64
PRank         float64
Mvot          float64
MRank         float64
Score         float64
Play           object
dtype: object

##### We check the datatypes to verify whether each column has the correct datatype or not and also to know whether there are any object columns which we need to encode.

In [ ]:
data.isnull().sum(axis = 0) #print the total number of missing values column-wise

Rk               0
Player.x         0
Player_ID        0
Pos1             0
Pos2          1396
Age              0
Tm               0
G                0
GS               0
MP               0
FG               0
FGA              0
FG.              4
X3P              0
X3PA             0
X3P.            99
X2P              0
X2PA             0
X2P.            15
eFG.             4
FT               0
FTA              0
FT.             47
ORB              0
DRB              0
TRB              0
AST              0
STL              0
BLK              0
TOV              0
PF               0
PTS              0
Salary          62
mean_views     138
Season           0
Conference       0
Role             0
Fvot             0
FRank            0
Pvot           159
PRank          159
Mvot           404
MRank          404
Score            0
Play             0
dtype: int64

In [ ]:
data.isnull().sum(axis = 1) #print the total number of missing values row-wise

0       6
1       5
2       5
3       3
4       3
       ..
1403    1
1404    1
1405    4
1406    1
1407    1
Length: 1408, dtype: int64

In [ ]:
data.isnull().sum(axis = 1) > 4   #mark the rows as True if they fulfill the mentioned condition and false otherwise

0        True
1        True
2        True
3       False
4       False
        ...
1403    False
1404    False
1405    False
1406    False
1407    False
Length: 1408, dtype: bool

In [ ]:
data[data.isnull().sum(axis = 1) > 5] #print the rows which have more than 5 missing values

,Rk,Player.x,Player_ID,Pos1,Pos2,Age,Tm,G,GS,MP,...,Conference,Role,Fvot,FRank,Pvot,PRank,Mvot,MRank,Score,Play
0,170,A.J. Hammons,hammoaj01,C,NaN,24,DAL,22,0,7.4,...,West,Front,786,123,NaN,NaN,NaN,NaN,83.5,No
16,443,Anderson VarejÃ£o,varejan01,C,NaN,34,GSW,14,1,6.6,...,West,Front,1724,40,NaN,NaN,NaN,NaN,42.0,No
27,341,Arinze Onuaku,onuakar01,C,NaN,29,ORL,8,0,3.5,...,Est,Front,216,129,NaN,NaN,NaN,NaN,90.0,No
37,60,Bobby Brown,brownbo02,PG,NaN,32,HOU,25,0,4.9,...,West,Back,206,70,NaN,NaN,NaN,NaN,52.0,No
48,378,Brian Roberts,roberbr01,PG,NaN,31,CHO,41,2,10.1,...,Est,Back,484,91,NaN,NaN,NaN,NaN,61.8,No
51,67,Bruno Caboclo,cabocbr01,SF,NaN,21,TOR,9,0,4.4,...,Est,Front,5185,66,NaN,NaN,NaN,NaN,58.5,No
54,302,C.J. Miles,milescj01,SF,NaN,29,IND,76,29,23.4,...,Est,Front,1965,95,NaN,NaN,NaN,NaN,73.0,No
55,455,C.J. Watson,watsocj01,PG,NaN,32,ORL,62,9,16.3,...,Est,Back,369,92,NaN,NaN,NaN,NaN,62.2,No
56,463,C.J. Wilcox,wilcocj01,SG,NaN,26,ORL,22,0,4.9,...,Est,Back,287,93,NaN,NaN,NaN,NaN,62.8,No
62,109,Cheick Diallo,diallch01,PF,NaN,20,NOP,17,0,11.7,...,West,Front,877,119,NaN,NaN,NaN,NaN,81.5,No
63,342,Chinanu Onuaku,onuakch01,C,NaN,20,HOU,5,1,10.4,...,West,Front,6007,65,NaN,NaN,NaN,NaN,54.5,No
78,235,Damian Jones,jonesda03,C,NaN,21,GSW,10,0,8.5,...,West,Front,12176,46,NaN,NaN,NaN,NaN,45.0,No
86,204,Danuel House,houseda01,SG,NaN,23,WAS,1,0,1.0,...,Est,Front,653,121,2.0,40.0,NaN,NaN,73.5,No
91,259,David Lee,leeda02,PF,NaN,33,SAS,79,10,18.7,...,West,Front,23334,33,NaN,NaN,NaN,NaN,38.5,No
107,236,Derrick Jones,jonesde02,SF,NaN,19,PHO,32,8,17.0,...,West,Front,505,129,NaN,NaN,NaN,NaN,86.5,No
112,103,Dewayne Dedmon,dedmode01,C,NaN,27,SAS,76,37,17.5,...,West,Front,17245,39,NaN,NaN,NaN,NaN,41.5,No
113,101,Deyonta Davis,davisde01,C,NaN,20,MEM,36,0,6.6,...,West,Front,1213,113,NaN,NaN,NaN,NaN,78.5,No
114,415,Diamond Stone,stonedi01,C,NaN,19,LAC,7,0,3.4,...,West,Front,952,117,NaN,NaN,NaN,NaN,80.5,No
155,280,Ian Mahinmi,mahinia01,C,NaN,30,WAS,31,0,17.9,...,Est,Front,1258,108,NaN,NaN,NaN,NaN,79.5,No
169,360,Jakob PÃ¶ltl,poeltja01,C,NaN,21,TOR,54,4,11.6,...,Est,Front,42,73,NaN,NaN,NaN,NaN,62.0,No
176,237,James Jones,jonesja02,SF,NaN,36,CLE,48,2,7.9,...,Est,Front,16782,33,NaN,NaN,NaN,NaN,42.0,No
201,479,Joe Young,youngjo01,PG,NaN,24,IND,33,0,4.1,...,Est,Back,781,85,NaN,NaN,NaN,NaN,58.8,No
214,195,Jordan Hill,hilljo01,C,NaN,29,MIN,7,0,6.7,...,West,Front,881,118,NaN,NaN,NaN,NaN,81.0,No
225,169,Justin Hamilton,hamilju01,C,NaN,26,BRK,64,7,18.4,...,Est,Front,1873,96,NaN,NaN,NaN,NaN,73.5,No
229,291,K.J. McDaniels,mcdankj01,SF,NaN,23,BRK,49,0,10.3,...,West,Back,8164,40,NaN,NaN,NaN,NaN,37.0,No
261,467,Lou Williams,willilo02,SG,NaN,30,HOU,81,1,24.6,...,West,Back,2997,27,NaN,NaN,NaN,NaN,30.5,No
278,429,Marcus Thornton,thornma01,SG,NaN,29,WAS,33,1,17.4,...,Est,Back,774,86,NaN,NaN,NaN,NaN,59.2,No
355,191,Roy Hibbert,hibbero01,C,NaN,30,DEN,48,13,14.2,...,Est,Front,1984,94,NaN,NaN,NaN,NaN,72.5,No
372,278,Sheldon Mac,mcclesh01,SG,NaN,24,WAS,30,3,9.6,...,Est,Back,855,83,NaN,NaN,NaN,NaN,57.8,No
375,196,Solomon Hill,hillso01,SF,NaN,25,NOP,80,71,29.7,...,West,Front,855,121,NaN,NaN,NaN,NaN,82.5,No
380,484,Stephen Zimmerman,zimmest01,C,NaN,20,ORL,19,0,5.7,...,Est,Front,767,119,NaN,NaN,NaN,NaN,85.0,No
381,331,Steve Novak,novakst01,PF,NaN,33,MIL,8,0,2.8,...,Est,Front,3909,75,NaN,NaN,NaN,NaN,63.0,No
384,454,T.J. Warren,warretj01,SF,NaN,23,PHO,66,59,31.0,...,West,Front,2275,94,NaN,NaN,NaN,NaN,69.0,No
430,373,Willie Reed,reedwi02,C,NaN,26,MIA,71,5,14.5,...,Est,Front,1062,112,NaN,NaN,NaN,NaN,81.5,No
472,348,Ben Moore,moorebe01,PF,NaN,22,IND,2,0,4.5,...,Est,Front,267,136,0.0,74.0,0.0,8.0,158.5,No
904,307,Tyler Lydon,lydonty01,PF,NaN,21,DEN,1,0,2.0,...,West,Front,850,135,1.0,47.0,0.0,9.0,118.2,No
1089,282,George King,kingge03,SF,NaN,25,PHO,1,0,6.0,...,West,Front,2964,119,0.0,84.0,0.0,8.0,152.0,No

In [ ]:
data = data[data.isnull().sum(axis = 1) <= 5]  #filter out the rows which has more than 5 missing values

In [ ]:
data.isnull().sum()

Rk               0
Player.x         0
Player_ID        0
Pos1             0
Pos2          1359
Age              0
Tm               0
G                0
GS               0
MP               0
FG               0
FGA              0
FG.              0
X3P              0
X3PA             0
X3P.            81
X2P              0
X2PA             0
X2P.            11
eFG.             0
FT               0
FTA              0
FT.             40
ORB              0
DRB              0
TRB              0
AST              0
STL              0
BLK              0
TOV              0
PF               0
PTS              0
Salary          52
mean_views     124
Season           0
Conference       0
Role             0
Fvot             0
FRank            0
Pvot           126
PRank          126
Mvot           370
MRank          370
Score            0
Play             0
dtype: int64

In [ ]:
data.shape  #check the shape again after row deletion

(1371, 45)

In [ ]:
data.drop(columns = 'Pos2', inplace = True) #drop the Pos2 column since more than 95% of its values are missing

In [ ]:
data = data.fillna(0) #fill the rest of missing values in the dataframe with 0

In [ ]:
data.duplicated().sum() #check for the number of duplicate rows

np.int64(0)

In [ ]:
data.drop_duplicates(inplace = True)  #drop the duplicate rows, if any

In [ ]:
data.drop(columns = ['Player.x', 'Player_ID'], inplace = True)  #drop these 2 columns since they are not useful for ML process

#### **Encode the categorical columns**

In [ ]:
obj_cols = data.select_dtypes('object').columns #select the column names of the columns which are of the object type

In [ ]:
obj_cols  #list of columns which are object type

Index(['Pos1', 'Tm', 'Season', 'Conference', 'Role', 'Play'], dtype='object')

In [ ]:
le = LabelEncoder()

for col in obj_cols:
  data[col] = le.fit_transform(data[col])

In [ ]:
#check for data imbalance
data['Play'].value_counts()

Play
0    1298
1      73
Name: count, dtype: int64

### **Machine Learning Process**

In [ ]:
X = data.drop(columns = 'Play') #store the input columns in X
y = data['Play']  #store the output column in y

In [ ]:
#split the data into training and test sets and use stratified sampling since the data is imbalanced
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 100, stratify = y)

#### **Mean Centering/Scaling/Standardization of the Data**

- Always perform this process after splitting the data into training and test.

In [ ]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

#### **Apply the Logistic Regression on the data**

In [ ]:
log_reg = LogisticRegression()
log_reg.fit(X_train_scaled, y_train)

LogisticRegression()

In [ ]:
log_reg.coef_   #print the coefficients (beta1 to beta42), which are weightage of each column

array([[ 0.55599738,  0.20563577,  0.68021607,  0.10722513,  1.57491189,
         1.07973303, -0.67160553,  0.41627396,  0.04806734,  0.02483851,
         0.58406804,  0.34452455, -0.55838499,  0.10080902, -0.18136329,
        -0.64537331,  0.20904553, -0.19200101,  0.148108  , -0.47414991,
        -0.10029033,  0.2153693 ,  0.23042837,  0.75398891,  0.06944723,
         0.19404955, -0.7295217 , -0.71186912,  0.32398553,  0.28350647,
         0.36893066,  0.05812181,  0.17763094,  0.44381383, -0.20531763,
        -0.87151468,  0.81503037, -0.39114073,  0.88706089,  0.01481096,
        -1.18597038]])

In [ ]:
y_pred = log_reg.predict(X_test_scaled)

In [ ]:
accuracy_score(y_test, y_pred)  #accuracy_score is unreliable in the case of imbalance data, so we don't trust it

0.96

In [ ]:
roc_auc_score(y_test, y_pred) #this is the correct performance of the model

np.float64(0.7275641025641026)

### **Now we will transform the data with PCA and check the performance of the model using the PCA transformed data**